### PR TITLE
Fix voice transcription

### LINKED ISSUE #945: [BUG] voice package is not being used - `voice.GroqTranscriber` is not part of the process any more
## Quick Summary

Voice messages are broken since v0.2.0. I don't see any more references to `voice.NewGroqTranscriber` or to the `voice` package in general anywhere in the code.

##  Environment & Tools
- **PicoClaw Version:** v0.2.0
- **Go Version:** n/a
- **AI Model & Provider:** n/a
- **Operating System:** Docker
- **Channels:** Telegram

## 📸 Steps to Reproduce
1. Add a groq API key to `model_list` section
2. Also add a groq API key to deprecated `providers` section
3. Send a voice message via Telegram to picoclaw

## ❌ Actual Behavior

- Picoclaw only sees `[voice]`

## ✅ Expected Behavior

- Transcriber should kick in

### PR DESCRIPTION
**Pull request by dim**
## 📝 Description

Addresses #945

## 🗣️ Type of Change
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📖 Documentation update
- [ ] ⚡ Code refactoring (no functional changes, no api changes)

## 🤖 AI Code Generation
- [ ] 🤖 Fully AI-generated (100% AI, 0% Human)
- [x] 🛠️ Mostly AI-generated (AI draft, Human verified/modified)
- [ ] 👨‍💻 Mostly Human-written (Human lead, AI assisted or none)

## 🔗 Related Issue

Fixes #945 

## 📚 Technical Context (Skip for Docs)
- **Reference URL:**
- **Reasoning:**

## 🧪 Test Environment
- **Hardware:** Raspberry Pi 5
- **OS:** Debian 13
- **Model/Provider:** MiniMax M25 + Groq Whisper
- **Channels:** Telegram

## 📸 Evidence (Optional)

```
2026/03/01 08:29:59 [2026-03-01T08:29:59Z] [INFO] agent: Processing message from telegram:telegram:REDACTED: [voice] {channel=telegram, chat_id=REDACTED, sender_id=telegram:REDACTED, session_key=}
2026/03/01 08:29:59 [2026-03-01T08:29:59Z] [INFO] voice: Starting transcription {audio_file=/tmp/picoclaw_media/452372f1_file_6.oga.ogg}
2026/03/01 08:29:59 [2026-03-01T08:29:59Z] [INFO] voice: Transcription completed successfully {text_length=45, language=, duration_seconds=0, transcription_preview= Let me check if voice recognition now works.}
2026/03/01 08:29:59 [2026-03-01T08:29:59Z] [INFO] agent: Routed message {agent_id=main, session_key=agent:main:telegram:direct:REDACTED, matched_by=default}
2026/03/01 08:30:05 [2026-03-01T08:30:05Z] [INFO] agent: LLM response without tool calls (direct answer) {agent_id=main, iteration=1, content_chars=294}
2026/03/01 08:30:05 [2026-03-01T08:30:05Z] [INFO] agent: Response: Hey, I can read that! 🎉
```

## ☑️ Checklist
- [x] My code/docs follow the style of this project.
- [x] I have performed a self-review of my own changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: cmd/picoclaw/internal/gateway/helpers.go [hunk 1]
```diff
@@ -134,6 +136,22 @@ func gatewayCmd(debug bool) error {
 	agentLoop.SetChannelManager(channelManager)
 	agentLoop.SetMediaStore(mediaStore)
 
+	// Wire up voice transcription if Groq API key is available
+	groqAPIKey := cfg.Providers.Groq.APIKey
```
Comment (xiaket) [inline cmd/picoclaw/internal/gateway/helpers.go]: Longer term, we may want to consider multiple transcribe providers and how can we prioritise them. For now this works and address an issue, I'm happy with it.

**Review by xiaket — APPROVED** [review]
LGTM

File: cmd/picoclaw/internal/gateway/helpers.go (hunk 1 above)
Comment (dim) [reply cmd/picoclaw/internal/gateway/helpers.go]: @xiaket let me address this then slightly more elegantly

**Review by nikolasdehor — APPROVED** [review]
LGTM. This is a well-structured fix that moves voice transcription from channel-specific (Telegram only) to agent-level, making it work across all channels.

Key improvements:
1. Transcriber interface with Name() and Transcribe() methods -- clean abstraction
2. DetectTranscriber auto-detects Groq from either direct provider config or model_list entries
3. Agent-level transcription via transcribeAudioInMessage replaces audio annotations [voice] with transcribed text
4. Falls back gracefully: if transcription fails, the annotation is left as-is (empty string appended)
5. README updates across all translations correctly reflect the change

The regex-based annotation replacement is clean: audioAnnotationRe matches [voice] and [audio:*] patterns, and transcriptions are applied in order. Remaining transcriptions (more audio than annotations) are appended with newlines.

Test coverage is thorough: interface satisfaction, DetectTranscriber with various configs, actual transcription with mocked HTTP server, API errors, and missing files. Good work.

**Review by afjcjsbx — APPROVED** [review]
LGTM! could you fix the lint?

**Review by lxowalle — APPROVED** [review]

**Comment by Orgmar** [comment]
@dim Thanks for fixing the voice transcription issue! Audio handling bugs can be tough to track down, glad this one got sorted out.

We have a **PicoClaw Dev Group** on Discord where contributors connect and share ideas. If you'd like to join, send an email to `support@sipeed.com` with the subject `[Join PicoClaw Dev Group] dim` and we'll send the invite!

**Comment by dim** [comment]
@Orgmar thanks, that's kind. I am a bit busy at the moment but would be very happy to join in a few weeks time. Will email `support@sipeed.com` as suggested. Thanks again!
