### PR TITLE
fix(providers): support per-model request_timeout in model_list

### LINKED ISSUE #637: [Feature] Make hardcoded `request_timeout` configurable in `config.json`
## 🎯 The Goal / Use Case
OpenAI-compatible provider has 120sec hardcoded timeout for request, which means Ollama will go through that part of the code. When using bigger Ollama local models, or running on weak machine it can take much more than 2min for response.

By making it configurable as `request_timeout` in `config.json` the need to set "perfect" hardcoded timeout is eliminated.
## 💡 Proposed Solution
Add support for `request_timeout` in `config.json` in `model_list`.

## 🚦 Impact & Roadmap Alignment
- [x] This is a Core Feature
- [ ] This is a Nice-to-Have / Enhancement
- [ ] This aligns with the current Roadmap

### PR DESCRIPTION
**Pull request by 0xYiliu**
## 📝 Description

Add per-model `request_timeout` support for OpenAI-compatible HTTP providers to fix slow local model timeout failures (Issue #637). This keeps backward compatibility with the previous 120s default while allowing model-specific overrides from `model_list`.

## 🗣️ Type of Change
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 📖 Documentation update
- [ ] ⚡ Code refactoring (no functional changes, no api changes)

## 🤖 AI Code Generation
- [ ] 🤖 Fully AI-generated (100% AI, 0% Human)
- [x] 🛠️ Mostly AI-generated (AI draft, Human verified/modified)
- [ ] 👨‍💻 Mostly Human-written (Human lead, AI assisted or none)

## 🔗 Related Issue

Fixes #637

## 📚 Technical Context (Skip for Docs)
- **Reference URL:**
  - https://github.com/sipeed/picoclaw/issues/637
  - https://pkg.go.dev/net/http#Client
- **Reasoning:**
  - Add `request_timeout` to `ModelConfig` and propagate it through provider factory -> HTTP provider -> OpenAI-compatible provider constructor.
  - Use `<= 0` fallback semantics to preserve existing default timeout behavior (`120s`).
  - Cover parsing, default behavior, override behavior, and factory propagation with tests.

## 🧪 Test Environment
- **Hardware:** x86_64 PC
- **OS:** Linux
- **Model/Provider:** OpenAI-compatible providers via `model_list` (openai/anthropic-protocol branch in factory path)
- **Channels:** N/A

## 📸 Evidence (Optional)
<details>
<summary>Click to view Logs/Screenshots</summary>

- `make check` (environment note: local runner lacks `golangci-lint` binary)
- `GOLANGCI_LINT=echo make check` passed:
  - deps verified
  - fmt target executed
  - go vet passed
  - go test ./... passed (including new timeout tests)

</details>

## ☑️ Checklist
- [x] My code/docs follow the style of this project.
- [x] I have performed a self-review of my own changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: pkg/providers/openai_compat/provider.go [hunk 1]
```diff
@@ -34,13 +34,27 @@ type Provider struct {
...
+
 func NewProvider(apiKey, apiBase, proxy string) *Provider {
 	return NewProviderWithMaxTokensField(apiKey, apiBase, proxy, "")
 }
 
 func NewProviderWithMaxTokensField(apiKey, apiBase, proxy, maxTokensField string) *Provider {
+	return NewProviderWithMaxTokensFieldAndTimeout(apiKey, apiBase, proxy, maxTokensField, 0)
+}
+
+func NewProviderWithMaxTokensFieldAndTimeout(
```
Comment (xiaket) [inline pkg/providers/openai_compat/provider.go]: I think more idiomatic go would use the Functional Options pattern to configure the behaviour of a new struct, as it would make adding options easier.

This can be addressed as a future improvement and should not block merging this PR.

Comment (xiaket) [reply pkg/providers/openai_compat/provider.go]: Just to be clear, I'm wishing for something like the following, please consider below to be pseudo code.

```
  func WithMaxTokensField(field string) Option {
      return func(p *Provider) {
          p.maxTokensField = field
      }
  }

  func WithRequestTimeout(timeout time.Duration) Option {
      return func(p *Provider) {
          p.httpClient.Timeout = timeout
      }
  }
```

File: README.md
Comment (xiaket) [inline README.md:1]: Can I bother you with the addition of these lines into other READMEs? AI generated translation is fine.

**Comment by 0xYiliu** [comment]
Thanks for the detailed review — all mentioned items are now addressed in the latest updates.

### 1) Functional Options for provider construction
Implemented for `openai_compat.Provider`:
- Added option pattern (`WithMaxTokensField`, `WithRequestTimeout`)
- Kept backward compatibility by preserving existing constructor wrappers
- Updated HTTP provider construction path to use options
- Added tests covering option behavior and timeout semantics

### 2) request_timeout migration consistency (including Ollama path)
- Added `request_timeout` support to legacy `providers` config (`ProviderConfig`)
- Ensured migration from legacy `providers` -> `model_list` carries `RequestTimeout` across providers
- Added migration test for timeout propagation

### 3) Sync docs across translated READMEs
Synced `request_timeout` guidance to:
- `README.ja.md`
- `README.pt-br.md`
- `README.vi.md`
- `README.fr.md`

This includes Quick Start JSON field, explanatory notes, and Custom Proxy/API example with `request_timeout`.

Validation:
- `make check` passes locally after the changes.

Commits pushed:
- `9d3f0af` refactor(providers): adopt functional options and preserve timeout migration
- `01ba912` docs(readme): sync request_timeout guidance across translated docs

**Comment by Orgmar** [comment]
@0xYiliu Per-model request_timeout is a really useful addition. Local models like Ollama can be significantly slower than cloud APIs, so the fixed 120s default was definitely causing unnecessary failures. The backward-compatible fallback logic is clean too.

We're building a **PicoClaw Dev Group** on Discord for contributors to connect and collaborate. If you'd like to join, send an email to `support@sipeed.com` with the subject `[Join PicoClaw Dev Group] 0xYiliu` and we'll send you the invite link.
