### PR TITLE
fix: detecting the external port that is being used, returning correct websocket

### LINKED ISSUE #1737: Launcher mode: Missing port 18800 documentation for WebSocket connections
### Environment
- **Version**: v0.2.3 (latest from main branch)
- **Deployment**: Docker (`docker.io/sipeed/picoclaw:launcher`)
- **LLM Backend**: Ollama (remote instance)
- **Model**: deepseek-r1-tools-fixed:14b (verified working)
- **OS**: Linux 6.8.0-106-generic (Ubuntu)

### Issue
The web UI chat input is permanently disabled with a "not-allowed" cursor (⛔), despite:
- Gateway running successfully (`gateway_status: "running"`, PID: 18)
- Model configured and responding correctly
- CLI agent working perfectly
- Pico WebSocket endpoint available with valid token

### What Works
```bash
# Backend completely functional
$ curl http://localhost:8080/api/gateway/status
{"gateway_status":"running","pid":18,"boot_default_model":"deepseek14b","config_default_model":"deepseek14b"}

# Model responds correctly via Ollama
$ curl -X POST http://<ollama-host>:11434/v1/chat/completions \
  -d '{"model":"deepseek-r1-tools-fixed:14b","messages":[{"role":"user","content":"hi"}]}'
# Response: "Hello! How can I assist you today?"

# CLI agent works perfectly
$ docker compose exec picoclaw-launcher picoclaw agent -m "what is 2+2?"
# Output: "The answer is **4**."

# Pico channel enabled
$ curl http://localhost:8080/api/pico/token
{"enabled":true,"token":"<redacted>","ws_url":"ws://localhost:18800/pico/ws"}
```

#### Frontend Code (chat-composer.tsx:25)
```typescript
const canInput = isConnected && hasDefaultModel
```

The chat input requires **BOTH**:
1. `isConnected` - WebSocket connection state
2. `hasDefaultModel` - Model configured

#### WebSocket Connection Logic (controller.ts:111-116)
```typescript
if (
  store.get(gatewayAtom).status !== "running" ||
  needsActiveSessionHydration()
) {
  return  // NO CONNECTION ATTEMPT
}
```

**The WebSocket won't even attempt to connect** unless `gatewayAtom.status === "running"`.

#### API Reports Gateway Running
```json
{
  "gateway_status": "running",
  "boot_default_model": "deepseek14b",
  "config_default_model": "deepseek14b",
  "gateway_start_allowed": true,
  "gateway_restart_required": false,
  "pid": 18
}
```

#### Frontend State Query
```bash
$ curl http://localhost:8080/api/config | python3 -c "import json,sys; d=json.load(sys.stdin); print('Default model:', d.get('agents',{}).get('defaults',{}).get('model_name'))"
Default model:   # EMPTY!
```

**The frontend `/api/config` returns empty default model** despite backend showing "deepseek14b".

#### Launcher Logs Show Gateway Running
```
picoclaw-launcher  | 2026/03/18 01:53:19 Gateway health status: 200
picoclaw-launcher  | 2026/03/18 01:53:19 GET /api/gateway/status 200 1.994495ms
```

### Configuration Used
```json
{
  "agents": {
    "defaults": {
      "workspace": "~/.picoclaw/workspace",
      "model_name": "deepseek",
      "max_tokens": 8192,
      "temperature": 0.7,
      "max_tool_iterations": 20
    },
    "list": [
      {
        "agent_id": "main",
        "model_name": "deepseek"
      }
    ]
  },
  "model_list": [
    {
      "model_name": "deepseek",
      "model": "ollama/deepseek-r1-tools-fixed:14b",
      "api_base": "http://<ollama-host>:11434/v1",
      "api_key": "ollama"
    }
  ],
  "gateway": {
    "host": "0.0.0.0",
    "port": 18790
  },
  "channels": {
    "pico": {
      "enabled": true,
      "token": "",
      "ping_interval": 30,
      "read_timeout": 60,
      "write_timeout": 10,
      "max_connections": 100,
      "allow_from": []
    }
  }
}
```

### Suspected Issue

Either:
1. **Frontend state management bug**: Gateway polling (`use-gateway.ts`) updates `gatewayAtom` but WebSocket connection logic doesn't trigger
2. **API inconsistency**: `/api/gateway/status` returns different data than `/api/config` for default model
3. **Race condition**: WebSocket connection attempt happens before gateway state propagates to frontend store

### Steps to Reproduce
1. Deploy with Docker: `docker compose -f docker-compose.deploy.yml --profile launcher up -d`
2. Configure Ollama model via web UI or config.json (remote Ollama instance)
3. Verify gateway is running: `curl http://localhost:8080/api/gateway/status`
4. Open web UI in browser
5. Observe: Chat input has ⛔ cursor and is disabled

### Expected Behavior
Chat input should be enabled when:
- Gateway status API returns `"gateway_status": "running"`
- Default model is configured and responding

### Workaround
Use CLI agent directly:
```bash
docker compose exec picoclaw-launcher picoclaw agent -m "your message"
```

### Additional Context
- Browser: Tested with clearing cache, incognito mode
- Network: Confirmed no firewall issues, localhost access works
- Multiple restart attempts: Issue persists across full container recreation
- Frontend polling active: `/api/gateway/status` requests visible every 2 seconds

---

**This appears to be a frontend state synchronization issue** where the backend correctly reports gateway as running with a configured model, but the frontend WebSocket connection logic never receives the "running" status to trigger connection, leaving chat permanently disabled.

### PR DESCRIPTION
**Pull request by lepotatoguy**
## 📝 Description

This PR fixes the root cause of the WebUI chat input being disabled (stop sign cursor) when using custom ports.

### Problem
When running the launcher with a custom port (e.g. Docker GUI mapping 46569 -> 18800, Tailscale, etc.), the frontend loads, but the chat box remains disabled.

Because the `/api/pico/token` endpoint was **hardcoding** the WebSocket URL to port `18800`.

## 🗣️ Type of Change
- [X] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📖 Documentation update
- [ ] ⚡ Code refactoring (no functional changes, no api changes)

## 🤖 AI Code Generation
- [ ] 🤖 Fully AI-generated (100% AI, 0% Human)
- [X] 🛠️ Mostly AI-generated (AI draft, Human verified/modified)
- [ ] 👨‍💻 Mostly Human-written (Human lead, AI assisted or none)

## 🔗 Related Issue

Fixes #1737

## 🧪 Test Environment
- **Hardware:** Asus Zephyrus G14
- **OS:** Ubuntu 24.04.4

## ☑️ Checklist
- [ ] My code/docs follow the style of this project.
- [X] I have performed a self-review of my own changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lepotatoguy** [comment]
@yinwm Thanks for pointing that out. The failures were caused by my branch being behind `main`. Rebased onto the latest `main`; linter and tests are now passing locally.

**Comment by lepotatoguy** [comment]
Hi @yinwm, just wanted to gently follow up on this PR. I have rebased it again onto the latest main. Would really appreciate your feedback whenever you have a moment.

**Comment by lepotatoguy** [comment]
Hi @mengzhuo @alexhoshina, would you please be able to take a look at this PR and review it when you get a chance? Thanks!

File: web/backend/api/gateway_host.go [hunk 1]
```diff
@@ -93,16 +93,43 @@ func requestWSScheme(r *http.Request) string {
...
+		}
 	}
-	return requestWSScheme(r) + "://" + net.JoinHostPort(host, strconv.Itoa(wsPort)) + "/pico/ws"
+
+	// Priority 3: Fall back to the web server port (launcher port)
+	if wsPort == 0 {
+		wsPort = h.serverPort
+	}
+
+	// Priority 4: Ultimate fallback to default launcher port
```
Comment (mengzhuo) [inline web/backend/api/gateway_host.go]: I don't think this is right to do, since 0 means bind to any port that available for OS

Comment (lepotatoguy) [reply web/backend/api/gateway_host.go]: Thanks for pointing that @mengzhuo. If serverPort is 0 (OS-assigned), we shouldn't use it. So, I added a > 0 guard so it only falls back to serverPort when it's a real bound port. If it still needs any other change, please let me know. Thank you again!
