### PR TITLE
fix(skills): use registry-backed search for skills discovery

### LINKED ISSUE #928: skills search returns HTTP 404 in v0.2.0 (ClawHub registry mismatch)
### Summary
In `picoclaw v0.2.0`, `skills search` fails with:

`Failed to fetch skills list: HTTP 404`

This appears to be a client/registry endpoint mismatch rather than network outage.

### Version
- `picoclaw 0.2.0`
- Built from official release package

### Reproduction
1. Fresh install of `picoclaw v0.2.0`
2. Configure default ClawHub registry (base URL set, default/empty registry paths)
3. Run:

```bash
picoclaw skills search github
```

### Actual result
```text
Searching for available skills...
✗ Failed to fetch skills list: failed to fetch skills list: HTTP 404
```

### Expected result
Search results are returned for `github` skill.

### Additional observations
- Direct HTTP call to ClawHub search endpoint returns valid JSON:
  - `GET https://clawhub.ai/api/search?q=github` -> `200` with result payload
- Trying registry path overrides in config did not resolve this in v0.2.0:
  - `/api/search`
  - `/api/v1/search`
  - `/api/skills`
  - `/api/v1/skills`
- `skills list-builtin` also fails in this environment with:
  - `Error reading builtin skills: .../picoclaw/skills: no such file or directory`

### Questions
1. What are the expected ClawHub registry endpoints for `skills search` in v0.2.0?
2. Is this fixed in a newer version?
3. Is there a supported config override for search/list/download paths that works with current ClawHub API?

### Temporary workaround
Install skills directly by source (e.g., direct install command) instead of `skills search`.

### PR DESCRIPTION
**Pull request by dwizzle204**
## 📝 Description
Fixes `skills search` returning 404 by removing the stale hardcoded skills index lookup and using configured skill registries (ClawHub) for discovery.

This keeps search aligned with the registry system already used elsewhere in skills workflows.

## 🗣️ Type of Change
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📖 Documentation update
- [ ] ⚡ Code refactoring (no functional changes, no api changes)

## 🤖 AI Code Generation
- [ ] 🤖 Fully AI-generated (100% AI, 0% Human)
- [x] 🛠️ Mostly AI-generated (AI draft, Human verified/modified)
- [ ] 👨‍💻 Mostly Human-written (Human lead, AI assisted or none)

## 🔗 Related Issue
Fixes #928

## 📚 Technical Context (Skip for Docs)
- **Reference URL:** https://github.com/sipeed/picoclaw/issues/928
- **Reasoning:**
  - `skills search` currently calls a hardcoded URL (`https://raw.githubusercontent.com/sipeed/picoclaw-skills/main/skills.json`) that returns 404.
  - Registry search infrastructure already exists (`RegistryManager`, `ClawHubRegistry`) and should be the source of truth.
  - This patch switches `skills search` to registry-backed search and preserves existing error prefix (`Failed to fetch skills list`) for CLI consistency.

## 🧪 Test Environment
- **Hardware:** x86_64 Linux VM
- **OS:** Ubuntu 20.04
- **Model/Provider:** N/A (CLI skills command path)
- **Channels:** N/A

## 📸 Evidence (Optional)
<details>
<summary>Click to view Logs/Screenshots</summary>

Local verification:
- `go generate ./...` ✅
- `make check` ✅

</details>

## ☑️ Checklist
- [x] My code/docs follow the style of this project.
- [x] I have performed a self-review of my own changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: cmd/picoclaw/internal/skills/helpers.go [hunk 1]
```diff
@@ -215,34 +215,43 @@ func skillsListBuiltinCmd() {
 	}
 }
 
-func skillsSearchCmd(installer *skills.SkillInstaller) {
+func skillsSearchCmd(query string) {
 	fmt.Println("Searching for available skills...")
 
+	cfg, err := internal.LoadConfig()
+	if err != nil {
+		fmt.Printf("✗ Failed to fetch skills list: %v\n", err)
```
Comment (xiaket) [inline cmd/picoclaw/internal/skills/helpers.go]: This error message is misleading.

File: cmd/picoclaw/internal/skills/helpers.go [hunk 2]
```diff
@@ -215,34 +215,43 @@ func skillsListBuiltinCmd() {
...
+	registryMgr := skills.NewRegistryManagerFromConfig(skills.RegistryConfig{
+		MaxConcurrentSearches: cfg.Tools.Skills.MaxConcurrentSearches,
+		ClawHub:               skills.ClawHubConfig(cfg.Tools.Skills.Registries.ClawHub),
+	})
+
 	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
 	defer cancel()
 
-	availableSkills, err := installer.ListAvailableSkills(ctx)
+	results, err := registryMgr.SearchAll(ctx, query, 20)
```
Comment (xiaket) [inline cmd/picoclaw/internal/skills/helpers.go]: This magic number should be a const.

File: cmd/picoclaw/internal/skills/helpers.go [hunk 3]
```diff
@@ -215,34 +215,43 @@ func skillsListBuiltinCmd() {
...
+
+	registryMgr := skills.NewRegistryManagerFromConfig(skills.RegistryConfig{
+		MaxConcurrentSearches: cfg.Tools.Skills.MaxConcurrentSearches,
+		ClawHub:               skills.ClawHubConfig(cfg.Tools.Skills.Registries.ClawHub),
+	})
+
 	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
 	defer cancel()
 
-	availableSkills, err := installer.ListAvailableSkills(ctx)
```
Comment (xiaket) [inline cmd/picoclaw/internal/skills/helpers.go:224]: Please check whether we can remove this struct/method.

**Review by xiaket — CHANGES_REQUESTED** [review]
Please take a look and let me know when it's ready.

File: cmd/picoclaw/internal/skills/helpers.go (hunk 1 above)
Comment (dwizzle204) [reply cmd/picoclaw/internal/skills/helpers.go]: Fixed in c0c7964. Updated the config-load error text in `skillsSearchCmd` to `Failed to load config` so the message matches the failure source.

File: cmd/picoclaw/internal/skills/helpers.go (hunk 3 above)
Comment (dwizzle204) [reply cmd/picoclaw/internal/skills/helpers.go:224]: Checked and removed the legacy struct/method in c0c7964 (`AvailableSkill` and `ListAvailableSkills`) since search is now registry-backed and those are no longer used.

File: cmd/picoclaw/internal/skills/helpers.go (hunk 2 above)
Comment (dwizzle204) [reply cmd/picoclaw/internal/skills/helpers.go]: Fixed in c0c7964. Replaced the literal `20` with `const skillsSearchMaxResults = 20` and now pass that constant into `SearchAll`.

**Comment by dwizzle204** [comment]
Addressed all requested changes in c0c7964, replied to each thread, and resolved all three review threads. Ready for re-review. Thanks!

**Review by xiaket — APPROVED** [review]
LGTM

**Comment by Orgmar** [comment]
@dwizzle204 Switching skills search from the stale hardcoded index to the registry system is the right call. Having search aligned with how skills are actually managed avoids those confusing 404s.

We're putting together the **PicoClaw Dev Group** on Discord for contributors to collaborate. If you'd like to join, send an email to `support@sipeed.com` with the subject `[Join PicoClaw Dev Group] dwizzle204` and we'll send you the invite link.
