### PR TITLE
fix(tools): allow /dev/null redirection and add read/write sandbox split

### LINKED ISSUE #964: [BUG] Safety guard blocks redirecting to /dev/null commands
## Quick Summary

In "restrict_to_workspace" mode, when executing tool_call, if LLM generated a command which redirected stdout or stderr to /dev/null, picoclaw will block the command.

##  Environment & Tools
- **PicoClaw Version:** 0.2.0 release version
- **AI Model & Provider:** glm-4.7
- **Operating System:** Linux ArchVF2 6.12.18-cwt-6.0.0-2 #1 SMP PREEMPT_DYNAMIC Wed Dec 24 13:56:12 +07 2025 riscv64 GNU/Linux

## 📸 Steps to Reproduce
1. Ask picoclaw to execute **find /home/user/.picoclaw/workspace -name "init_skill.py"** command, log shows "Tool execution completed"
2. Ask picoclaw to execute **find /home/user/.picoclaw/workspace -name "init_skill.py" 2>/dev/null** command, log shows "Tool execution failed {tool=exec, duration=2, error=Command blocked by safety guard (path outside working dir)}"

## ❌ Actual Behavior

2026/03/01 23:39:43 [2026-03-01T15:39:43Z] [INFO] agent: Processing message from feishu:feishu:...: 请执行 find /home/user/.picoclaw/workspace -name "init_skill.py" 指令，并返回结果。 {c
hannel=feishu, chat_id=..., sender_id=feishu:..., session_key=}
2026/03/01 23:39:43 [2026-03-01T15:39:43Z] [INFO] agent: Routed message {agent_id=main, session_key=agent:main:feishu:direct:..., matched_by=default}
2026/03/01 23:39:45 [2026-03-01T15:39:45Z] [INFO] agent: LLM requested tool calls {agent_id=main, tools=[exec], count=1, iteration=1}
2026/03/01 23:39:45 [2026-03-01T15:39:45Z] [INFO] agent: Tool call: exec({"command":"find /home/user/.picoclaw/workspace -name \"init_skill.py\""}) {agent_id=main, tool=exec, iteration=1}
2026/03/01 23:39:45 [2026-03-01T15:39:45Z] [INFO] tool: Tool execution started {tool=exec, args=map[command:find /home/user/.picoclaw/workspace -name "init_skill.py"]}
2026/03/01 23:39:45 [2026-03-01T15:39:45Z] [INFO] tool: Tool execution completed {tool=exec, duration_ms=36, result_length=11}

2026/03/01 23:30:20 [2026-03-01T15:30:20Z] [INFO] agent: Processing message from feishu:feishu:...: 请执行 find /home/user/.picoclaw/workspace -name "init_skill.py" 2>/dev/null 指令，...
 {chat_id=..., sender_id=feishu:..., session_key=, channel=feishu}
2026/03/01 23:30:20 [2026-03-01T15:30:20Z] [INFO] agent: Routed message {agent_id=main, session_key=agent:main:feishu:direct:..., matched_by=default}
^[[6~^[[6~^[[A2026/03/01 23:30:22 [2026-03-01T15:30:22Z] [INFO] agent: LLM requested tool calls {agent_id=main, tools=[exec], count=1, iteration=1}
2026/03/01 23:30:22 [2026-03-01T15:30:22Z] [INFO] agent: Tool call: exec({"command":"find /home/user/.picoclaw/workspace -name \"init_skill.py\" 2\u003e/dev/null"}) {agent_id=main, tool=exec,
 iteration=1}
2026/03/01 23:30:22 [2026-03-01T15:30:22Z] [INFO] tool: Tool execution started {tool=exec, args=map[command:find /home/user/.picoclaw/workspace -name "init_skill.py" 2>/dev/null]}
2026/03/01 23:30:22 [2026-03-01T15:30:22Z] [ERROR] tool: Tool execution failed {tool=exec, duration=2, error=Command blocked by safety guard (path outside working dir)}

## ✅ Expected Behavior

redirect to /dev/null may be considered safe, so the latter command should not be blocked. （whitelist **/dev/null** in *nix operating systems）

### LINKED ISSUE #965: [BUG] Writing to /dev/mmcblk* and /dev/nvme* should also be blocked along with /dev/sd*
## Quick Summary

The exec tool blocks writing to **/dev/sd*** devices([pkg/tools/shell.go](https://github.com/sipeed/picoclaw/blob/3926585786b8757c7173d969f8f0ac9d922445b1/pkg/tools/shell.go#L37)). Many computing devices use **/dev/mmcblk*** and **/dev/nvme*** disk device names, so writing to these devices should also be blocked.

### PR DESCRIPTION
**Pull request by vowstar**
## 📝 Description

The safety guard blocks `2>/dev/null` when `restrict_to_workspace` is enabled, which makes glm-4.7 (and probably other models that like to silence stderr) basically unusable with workspace restriction turned on. Two things cause this: a deny pattern that should never have existed, and the workspace path checker treating `/dev/null` as "outside workspace".

While fixing that, I also noticed the device write blocklist only covers `/dev/sd*` -- no nvme, no mmcblk, nothing modern. And the sandbox has always been all-or-nothing for file tools, so I added a config knob to let reads roam free while keeping writes locked down.

## 🗣️ Type of Change
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📖 Documentation update
- [ ] ⚡ Code refactoring (no functional changes, no api changes)

## 🤖 AI Code Generation
- [ ] 🤖 Fully AI-generated (100% AI, 0% Human)
- [x] 🛠️ Mostly AI-generated (AI draft, Human verified/modified)
- [ ] 👨‍💻 Mostly Human-written (Human lead, AI assisted or none)

## 🔗 Related Issue

Closes #964
Closes #965

## 📚 Technical Context (Skip for Docs)
- **Reference URL:** https://github.com/sipeed/picoclaw/issues/964 https://github.com/sipeed/picoclaw/issues/965
- **Reasoning:** The root cause is two independent mechanisms both rejecting `/dev/null`: (1) a deny regex on line 48 that matches any redirect to `/dev/null`, and (2) the workspace path containment check extracting `/dev/null` as an absolute path and finding it outside the workspace. Fix removes the wrong deny pattern, adds a small whitelist of kernel pseudo-devices for the path check, expands the device blocklist to modern hardware, and introduces `allow_read_outside_workspace` so reads are not unnecessarily sandboxed.

## 🧪 Test Environment
- **Hardware:** x86_64 PC
- **OS:** Gentoo Linux 6.18.7
- **Model/Provider:** N/A (unit tests only)
- **Channels:** N/A

## 📸 Evidence (Optional)
<details>
<summary>Click to view Logs/Screenshots</summary>

All 108 tests in `pkg/tools` pass, including 3 new ones:

- `TestShellTool_DevNullAllowed` -- 6 variants of `/dev/null` redirection
- `TestShellTool_BlockDevices` -- 11 block device types
- `TestShellTool_SafePathsInWorkspaceRestriction` -- safe paths not rejected by workspace check

`pkg/config` and `pkg/agent` tests also pass.

</details>

## ☑️ Checklist
- [x] My code/docs follow the style of this project.
- [x] I have performed a self-review of my own changes.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: pkg/config/defaults.go [hunk 1]
```diff
@@ -10,13 +10,14 @@ func DefaultConfig() *Config {
...
-				Workspace:           "~/.picoclaw/workspace",
-				RestrictToWorkspace: true,
-				Provider:            "",
-				Model:               "",
-				MaxTokens:           32768,
-				Temperature:         nil, // nil means use provider default
-				MaxToolIterations:   50,
+				Workspace:                 "~/.picoclaw/workspace",
+				RestrictToWorkspace:       true,
+				AllowReadOutsideWorkspace: true,
```
Comment (xiaket) [inline pkg/config/defaults.go]: I have concern over this additional read access. I understand where you come from, but this is a behavior change from existing behavior.

I'm happy with this addition, but IMO it should be false by default.

**Comment by xiaket** [comment]
Also please resolve conflict and let me know ;)

File: pkg/config/defaults.go (hunk 1 above)
Comment (vowstar) [reply pkg/config/defaults.go]: Good point. Changed the default to false so existing behavior is preserved. Users who want unrestricted reads can opt in explicitly.

**Comment by vowstar** [comment]
Conflict resolved and rebased onto current main. Also addressed the default value concern -- `allow_read_outside_workspace` now defaults to `false`.

**Comment by vowstar** [comment]
@lxowalle Thanks for the suggestion. Added in 10884f7:

- `custom_allow_patterns` in exec config -- commands matching these skip deny pattern checks, so you can selectively permit things like `git push origin` without disabling the whole deny list.
- `allow_read_paths` and `allow_write_paths` regex lists under tools config -- when a path matches, file tools bypass the sandbox and go through hostFs directly. This lets you grant access to specific directories outside the workspace without opening everything up.

Both are empty by default so no behavior change.

**Review by lxowalle — APPROVED** [review]
LGTM

**Comment by Orgmar** [comment]
@vowstar The /dev/null redirection fix makes total sense. Blocking stderr silencing when workspace restriction is on would make a lot of models unusable in practice. Splitting read and write sandbox checks is a much cleaner design than a blanket deny.

We have a **PicoClaw Dev Group** on Discord where contributors share ideas and collaborate. If you're interested, send an email to `support@sipeed.com` with the subject `[Join PicoClaw Dev Group] vowstar` and we'll send you the invite link.
