### PR TITLE
fix: Templates update

### LINKED ISSUE #481: [BUG] temperature setting in config.json is ignored
## Quick Summary

I configured `"temperature": 1` in `~/.picoclaw/config.json` for the `openai` provider. However, when running the agent, the API request fails with a 400 error stating that the temperature sent was `0.7`. This suggests that the configuration is being ignored or overridden by an internal default value (likely 0.7).

## Environment & Tools

- **PicoClaw Version:** v0.1.2-90-g521359e (git: 521359ed) / Build: 2026-02-19T22:32:44+0900
- **Go Version:** go1.26.0
- **AI Model & Provider:** gpt-5-mini-2025-08-07 via OpenAI
- **Operating System:** Ubuntu (implied from logs)
- **Channels:** CLI

## 📸 Steps to Reproduce
1. Configure `~/.picoclaw/config.json` with `"temperature": 1` in `agents.defaults`.
2. Run the command: `picoclaw agent -m "Hello!"`
3. The execution fails with an API error.

## ❌ Actual Behavior
The API returns a 400 error indicating that the requested temperature was `0.7`, which is not supported by the model used (`gpt-5-mini-2025-08-07`).

```text
{agent_id=main, iteration=1, error=API request failed:
  Status: 400
  Body:   {
  "error": {
    "message": "Unsupported value: 'temperature' does not support 0.7 with this model. Only the default (1) value is supported.",
    "type": "invalid_request_error",
    "param": "temperature",
    "code": "unsupported_value"
  }
}}
```

## ✅ Expected Behavior
PicoClaw should respect the `temperature` value defined in `config.json` (1.0) and send it to the API, allowing the request to succeed.

## 💬 Additional Context
I also attempted to set the temperature via environment variables, but the result was the same (error shows 0.7 was sent):

```bash
PICOCLAW_AGENTS_DEFAULTS_TEMPERATURE=1 picoclaw agent -m "Hello!"
```

**My `~/.picoclaw/config.json`:**

```json
{
  "agents": {
    "defaults": {
      "workspace": "~/.picoclaw/workspace",
      "restrict_to_workspace": false,
      "provider": "openai",
      "model": "gpt-5-mini-2025-08-07",
      "max_tokens": 8192,
      "temperature": 1,
      "max_tool_iterations": 20
    }
  },
  "providers": {
    "openai": {
      "api_key": "sk-dummy",
      "api_base": "https://api.openai.com/v1",
      "web_search": true
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cointem**
## 🗣️ Type of Change
- [x] 🐞 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 📖 Documentation update
- [ ] ⚡ Code refactoring (no functional changes, no api changes)

## 🤖 AI Code Generation
- [ ] 🤖 Fully AI-generated (100% AI, 0% Human)
- [x] 🛠️ Mostly AI-generated (AI draft, Human verified/modified)
- [ ] 👨‍💻 Mostly Human-written (Human lead, AI assisted or none)

## 📚 Technical Context (Skip for Docs)
- **Reference URL:**
- **Reasoning:**

## 🧪 Test Environment
- **Hardware:** 
- **OS:** 
- **Model/Provider:** 
- **Channels:** 

## 📸 Evidence (Optional)
<details>
<summary>
image
</summary>

</details>

## ☑️ Checklist
- [x] My code/docs follow the style of this project.
- [x] I have performed a self-review of my own changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cointem** [comment]
refs #481

**Comment by huaaudio** [comment]
Hi @cointem , thanks for the PR! Could you also help fix the hardcoded config in `pkg/tools/subagent.go` and `pkg/tools/toolloop.go` so we can take care of this issue together in this PR? Thanks in advance!

**Comment by cointem** [comment]
> Hi @cointem , thanks for the PR! Could you also help fix the hardcoded config in `pkg/tools/subagent.go` and `pkg/tools/toolloop.go` so we can take care of this issue together in this PR? Thanks in advance!嗨，感谢你的提交！你能帮忙修复 `pkg/tools/subagent.go` 和 `pkg/tools/toolloop.go` 中的硬编码配置，这样我们就可以在这个提交中一起处理这个问题了？提前感谢！

ok, I'll  fix it

**Comment by cointem** [comment]
> Hi @cointem , thanks for the PR! Could you also help fix the hardcoded config in `pkg/tools/subagent.go` and `pkg/tools/toolloop.go` so we can take care of this issue together in this PR? Thanks in advance!

Hi, I have fixed it! @Huaaudio

File: pkg/agent/instance.go [hunk 1]
```diff
@@ -83,6 +83,11 @@ func NewAgentInstance(
 		maxTokens = 8192
 	}
 
+	temperature := defaults.Temperature
+	if temperature == 0 {
+		temperature = 0.7
```
Comment (huaaudio) [inline pkg/agent/instance.go]: The case of `temperature == 0` shall be respected as well, as it is intended for some use cases. By setting temperature = 0, you get zero fluctuations in LLM output. Consider using another value, e.g. `nil` for the default.

**Review by Huaaudio — CHANGES_REQUESTED** [review]
Thanks for the quick update! The only thing is that we want to distinguish between a user input of 0 temperature and "not provided."

File: pkg/agent/instance.go (hunk 1 above)
Comment (cointem) [reply pkg/agent/instance.go]: @Huaaudio  nil is default value for temperature now. And it's ok when setting 0 as value.

Comment (huaaudio) [reply pkg/agent/instance.go]: @cointem Great! Don't forget to push, and we are ready to go.

Comment (cointem) [reply pkg/agent/instance.go]: @Huaaudio It's strange — I have commits/changes on my branch, but they're not showing up in the pull request. And I can view the change in my repos.

Comment (cointem) [reply pkg/agent/instance.go]: image
There are 4 commits, but the pr has only 3 commits.

Comment (huaaudio) [reply pkg/agent/instance.go]: Okay, it looks like your commit [418956a](https://github.com/sipeed/picoclaw/commit/418956aa4549201d59aa8540e77c2623c848094b) got detached from the templates-update branch. It still exists but isn't part of any branch, so it won't be included in the PR. Could you cherry-pick it back and push?

**Comment by huaaudio** [comment]
Hi @cointem  thanks for the work! This is ready to be merged. Can you run `make fmt` to address the formatting issue and then commit? Thanks!

**Comment by cointem** [comment]
@Huaaudio  It's ok now! Thanks for your review!

**Comment by cointem** [comment]
@Huaaudio emmm, can you tell me how to join the Discord developer group？Please!

**Comment by huaaudio** [comment]
> @Huaaudio emmm, can you tell me how to join the Discord developer group？Please!

We have the PicoClaw Dev Group on Discord for contributors to connect and collaborate. If you'd like to join, email support@sipeed.com with the subject `[Join PicoClaw Dev Group] + Your GitHub account` and we'll send you the invite!
